# Archivo exclusivo para Producción (VPS)
# Este archivo expone el Frontend al mundo exterior en el puerto 80.
services:
  frontend:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.catalog-web.rule=Host(`catalog.raizdigital.com.ar`)"
      - "traefik.http.routers.catalog-web.entrypoints=websecure"
      - "traefik.http.routers.catalog-web.tls=true"
      - "traefik.http.routers.catalog-web.tls.certresolver=letsencrypt"
      - "traefik.http.services.catalog-web.loadbalancer.server.port=80"
    networks:
      - default
      - traefik-network

networks:
  traefik-network:
    external: true
